// cli/commands/prod/generate.ts — Pure file generation helpers for the prod wizard
// SPDX-License-Identifier: GPL-3.0-only

export interface DotEnvLocalValues {
  NEXT_PUBLIC_CONVEX_URL?: string;
  GITHUB_TOKEN?: string;
  GROQ_API_KEY?: string;
  CESIUM_BASE_URL?: string;
}

export interface MqttEnvValues {
  MQTT_BROKER_URL?: string;
  MQTT_USERNAME?: string;
  MQTT_PASSWORD?: string;
  CONVEX_URL?: string;
  CLOUDFLARE_TUNNEL_TOKEN?: string;
}

export interface VideoEnvValues {
  RTSP_URL_PATTERN?: string;
  PORT?: string;
  CLOUDFLARE_TUNNEL_TOKEN?: string;
}

export interface ComposePortRemap {
  /** Published (host) port */
  host: number;
  /** Container-internal target port */
  target: number;
  /** docker-compose service name */
  service: string;
}

function kv(key: string, value: string | undefined, commentIfEmpty = true): string {
  if (value && value.trim()) return `${key}=${value.trim()}`;
  return commentIfEmpty ? `# ${key}=` : '';
}

export function generateDotEnvLocal(values: DotEnvLocalValues): string {
  return [
    '# Altnautica Command — Environment Variables',
    '# Generated by CLI — gitignored, do not commit',
    '',
    '# Convex Backend',
    kv('NEXT_PUBLIC_CONVEX_URL', values.NEXT_PUBLIC_CONVEX_URL),
    '',
    '# API Keys',
    kv('GITHUB_TOKEN', values.GITHUB_TOKEN),
    kv('GROQ_API_KEY', values.GROQ_API_KEY),
    '',
    '# GCS Options',
    kv('CESIUM_BASE_URL', values.CESIUM_BASE_URL),
    '',
  ].join('\n');
}

export function generateMqttEnv(values: MqttEnvValues): string {
  return [
    '# MQTT Bridge — Environment Variables',
    '# Generated by CLI — gitignored, do not commit',
    '',
    kv('MQTT_BROKER_URL', values.MQTT_BROKER_URL ?? 'mqtt://mosquitto:1883', false),
    kv('MQTT_USERNAME', values.MQTT_USERNAME ?? 'ados', false),
    kv('MQTT_PASSWORD', values.MQTT_PASSWORD),
    kv('CONVEX_URL', values.CONVEX_URL),
    kv('CLOUDFLARE_TUNNEL_TOKEN', values.CLOUDFLARE_TUNNEL_TOKEN),
    '',
  ].join('\n');
}

export function generateVideoRelayEnv(values: VideoEnvValues): string {
  return [
    '# Video Relay — Environment Variables',
    '# Generated by CLI — gitignored, do not commit',
    '',
    kv('RTSP_URL_PATTERN', values.RTSP_URL_PATTERN ?? 'rtsp://host.docker.internal:8554/{deviceId}', false),
    kv('PORT', values.PORT ?? '3001', false),
    kv('CLOUDFLARE_TUNNEL_TOKEN', values.CLOUDFLARE_TUNNEL_TOKEN),
    '',
  ].join('\n');
}

/**
 * Generates a docker-compose.override.yml that remaps published ports.
 * Only generates overrides for ports that differ from the compose defaults.
 */
export function generateComposeOverride(remaps: ComposePortRemap[]): string {
  if (remaps.length === 0) return '';
  const serviceBlocks: Record<string, string[]> = {};
  for (const r of remaps) {
    if (!serviceBlocks[r.service]) serviceBlocks[r.service] = [];
    serviceBlocks[r.service].push(`      - "${r.host}:${r.target}"`);
  }
  const lines = [
    '# docker-compose.override.yml — Port remaps generated by CLI',
    '# Generated by CLI — commit this file only if it contains no secrets',
    'services:',
  ];
  for (const [svcName, ports] of Object.entries(serviceBlocks)) {
    lines.push(`  ${svcName}:`, '    ports:');
    lines.push(...ports);
  }
  lines.push('');
  return lines.join('\n');
}
