/**
 * Configurable PDF template — user picks which sections to include.
 *
 * Renders a header, selected sections in order, and a footer. Works for
 * both single-flight and multi-flight (logbook) exports.
 *
 * @license GPL-3.0-only
 */

import { Document, Page, View, Text } from "@react-pdf/renderer";
import { styles } from "../styles";
import { SECTION_COMPONENTS } from "../sections/all-sections";
import type { FlightRecord } from "@/lib/types";
import type { OperatorProfile, AircraftRecord } from "@/lib/types/operator";
import type { JurisdictionSpec } from "../../jurisdictions";

interface ConfigurablePdfProps {
  records: FlightRecord[];
  operator: OperatorProfile;
  aircraftIndex: Record<string, AircraftRecord>;
  spec: JurisdictionSpec;
  sections: string[];
}

export function ConfigurablePdf({
  records,
  operator,
  aircraftIndex,
  spec,
  sections,
}: ConfigurablePdfProps) {
  return (
    <Document>
      {records.map((record) => {
        const aircraft = aircraftIndex[record.droneId];
        return (
          <Page key={record.id} size="A4" style={styles.page}>
            {/* Header */}
            <View style={styles.cover}>
              <Text style={styles.brand}>ADOS MISSION CONTROL — FLIGHT REPORT</Text>
              <Text style={styles.title}>{record.customName ?? record.droneName}</Text>
              <Text style={styles.subtitle}>
                {spec.displayName} · {spec.regulator} · {spec.regulationRef}
              </Text>
              <Text style={{ fontSize: 8, color: "#6b6b7f", marginTop: 4 }}>
                Generated {new Date().toISOString().slice(0, 10)} · Record {record.id.slice(0, 8)}
              </Text>
            </View>

            {/* Selected sections */}
            {sections.map((sectionId) => {
              const Component = SECTION_COMPONENTS[sectionId];
              if (!Component) return null;
              return (
                <Component
                  key={sectionId}
                  record={record}
                  operator={operator}
                  aircraft={aircraft}
                />
              );
            })}

            {/* Footer */}
            <Text style={styles.footer}>
              {spec.retentionMonths > 0
                ? `Retain for ${spec.retentionMonths} months per ${spec.regulationRef}. `
                : ""}
              Generated by Altnautica ADOS Mission Control · altnautica.com
            </Text>
          </Page>
        );
      })}
    </Document>
  );
}
