import fs from 'node:fs';
import { ENV_FILE, ENV_EXAMPLE } from './paths.js';

export const ENV_KEYS = [
  'NEXT_PUBLIC_DEMO_MODE',
  'NEXT_PUBLIC_CONVEX_URL',
] as const;

export type EnvKey = (typeof ENV_KEYS)[number];

export const ENV_DESCRIPTIONS: Record<EnvKey, string> = {
  NEXT_PUBLIC_DEMO_MODE: 'Demo mode — mock flight engine with simulated drones',
  NEXT_PUBLIC_CONVEX_URL: 'Convex backend URL (optional — cloud fleet management)',
};

export function readEnvFile(filePath = ENV_FILE): Map<string, string> {
  const map = new Map<string, string>();
  if (!fs.existsSync(filePath)) return map;

  const content = fs.readFileSync(filePath, 'utf-8');
  for (const line of content.split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    const key = trimmed.slice(0, eqIdx).trim();
    const value = trimmed.slice(eqIdx + 1).trim();
    map.set(key, value);
  }
  return map;
}

export function writeEnvFile(filePath: string, entries: Map<string, string>): void {
  const lines: string[] = [
    '# Altnautica Command — Environment Variables',
    '# Generated by CLI. All variables are optional.',
    '',
  ];

  for (const key of ENV_KEYS) {
    const desc = ENV_DESCRIPTIONS[key];
    const value = entries.get(key);
    lines.push(`# ${desc}`);
    if (value !== undefined && value !== '') {
      lines.push(`${key}=${value}`);
    } else {
      lines.push(`# ${key}=`);
    }
    lines.push('');
  }

  fs.writeFileSync(filePath, lines.join('\n'), 'utf-8');
}

export function createFromExample(): boolean {
  if (!fs.existsSync(ENV_EXAMPLE)) return false;
  if (fs.existsSync(ENV_FILE)) return false; // Don't overwrite
  fs.copyFileSync(ENV_EXAMPLE, ENV_FILE);
  return true;
}
