// cli/lib/multi-env.ts — Multi-file environment variable management for tool .env files
// SPDX-License-Identifier: GPL-3.0-only

import fs from 'node:fs';
import path from 'node:path';
import { execSync } from 'node:child_process';
import { PROJECT_ROOT } from './paths.js';

export function readEnvMap(filePath: string): Map<string, string> {
  const map = new Map<string, string>();
  if (!fs.existsSync(filePath)) return map;
  for (const line of fs.readFileSync(filePath, 'utf-8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIdx = trimmed.indexOf('=');
    if (eqIdx === -1) continue;
    map.set(trimmed.slice(0, eqIdx).trim(), trimmed.slice(eqIdx + 1).trim());
  }
  return map;
}

/**
 * Verifies that filePath is covered by .gitignore before writing sensitive content.
 * Throws with a descriptive message if the file would not be ignored.
 */
export function assertGitignored(filePath: string): void {
  try {
    execSync(`git check-ignore -q "${filePath}"`, {
      stdio: 'pipe',
      cwd: PROJECT_ROOT,
      timeout: 5000,
    });
  } catch {
    throw new Error(
      `Refusing to write sensitive values to ${path.basename(filePath)}.\n` +
      `The file is not covered by .gitignore — add it before storing credentials.`
    );
  }
}

/**
 * Writes a .env file in key=value format with a header comment.
 * Calls assertGitignored before writing.
 * Keys with empty/undefined values are written as commented-out stubs.
 */
export function writeEnvMap(
  filePath: string,
  header: string,
  keys: readonly string[],
  values: Map<string, string>
): void {
  assertGitignored(filePath);
  const lines: string[] = [
    `# ${header}`,
    '# Generated by CLI — gitignored, do not commit',
    '',
  ];
  for (const key of keys) {
    const value = values.get(key);
    if (value !== undefined && value !== '') {
      lines.push(`${key}=${value}`);
    } else {
      lines.push(`# ${key}=`);
    }
  }
  lines.push('');
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, lines.join('\n'), 'utf-8');
}

/**
 * Reads an existing .env file, applies patches (key → value), and writes back.
 * An empty string value removes the key. Calls assertGitignored before writing.
 * Preserves keys not present in patches.
 */
export function patchEnvMap(filePath: string, patches: Record<string, string>): void {
  assertGitignored(filePath);
  const existing = readEnvMap(filePath);
  for (const [k, v] of Object.entries(patches)) {
    if (v === '') existing.delete(k);
    else existing.set(k, v);
  }
  const lines: string[] = ['# Edited by CLI — gitignored, do not commit', ''];
  for (const [k, v] of existing.entries()) {
    lines.push(`${k}=${v}`);
  }
  lines.push('');
  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, lines.join('\n'), 'utf-8');
}

/**
 * Copies examplePath to filePath if filePath does not exist.
 * Returns true if the file was created.
 */
export function createEnvIfMissing(filePath: string, examplePath: string): boolean {
  if (fs.existsSync(filePath)) return false;
  if (!fs.existsSync(examplePath)) return false;
  fs.copyFileSync(examplePath, filePath);
  return true;
}
